# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Birdy < Formula
  desc "Multi-account X/Twitter CLI with account rotation, in one Go binary"
  homepage "https://github.com/guzus/birdy"
  version "1.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/guzus/birdy/releases/download/v1.0.2/birdy_darwin_amd64.tar.gz"
      sha256 "3145009c5fa20716bf38bb75bf3f0c127cc26c518ae06cb06773431d4054b55b"

      define_method(:install) do
        bin.install "birdy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/guzus/birdy/releases/download/v1.0.2/birdy_darwin_arm64.tar.gz"
      sha256 "7fa90b089d03c2f90c4745675b1cc48ce04cec636e35d52ae8e862466dffb4b3"

      define_method(:install) do
        bin.install "birdy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/guzus/birdy/releases/download/v1.0.2/birdy_linux_amd64.tar.gz"
      sha256 "5e0a73649303cb3e5d771badd5cb3171b45a85d2aaa7e0db2439da53e6c3714a"
      define_method(:install) do
        bin.install "birdy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/guzus/birdy/releases/download/v1.0.2/birdy_linux_arm64.tar.gz"
      sha256 "cfa53e69501c93e3624c4c895bac3db5002bb8657fe843794c6b12bf39a96add"
      define_method(:install) do
        bin.install "birdy"
      end
    end
  end

  test do
    assert_match "birdy", shell_output("#{bin}/birdy version")
  end
end
